#ifndef ___CONFIG_HPP
#define ___CONFIG_HPP

#define HUMAN_SIZE 1
#define TERM 1000
#define HUMAN_INTERVAL 1
#define IMMUNE_INTERVAL 1
#define HUMAN_LAND_WIDTH 10
#define HUMAN_LAND_HEIGHT 10
#define TCELL_MINIMUM_SIZE 10
#define TCELL_LIFESPAN 10
#define CELL_LAND_WIDTH 10
#define CELL_LAND_HEIGHT 10
#define V_TAG 3

#endif
